default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV['DB_PASS'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: happy_farmer_development

test:
  <<: *default
  database: happy_farmer_test

production:
  <<: *default
  database: happy_farmer_production
  username: happy_farmer
  password: <%= ENV['HAPPY_FARMER_DATABASE_PASSWORD'] %>
